### ISSUE TITLE
Packaging 후 python 실행 error 

### ISSUE THREAD

**Issue by coooldoggy** [coooldoggy/PushExcelDivider#1]
Uncaught Exception:
Error: ModuleNotFoundError: No module named 'pandas'
at PythonShell.parseError (/Users/ats/dev/workspace_vs/PushExcelDivider/build/mac/PushExcelDivider.app/Contents/Resources/app.asar/node_modules/python-shell/index.js:261:21)
at terminateIfNeeded (/Users/ats/dev/workspace_vs/PushExcelDivider/build/mac/PushExcelDivider.app/Contents/Resources/app.asar/node_modules/python-shell/index.js:144:32)
at ChildProcess.<anonymous> (/Users/ats/dev/workspace_vs/PushExcelDivider/build/mac/PushExcelDivider.app/Contents/Resources/app.asar/node_modules/python-shell/index.js:136:13)
at ChildProcess.emit (events.js:315:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
----- Python Traceback -----
File "/Users/ats/dev/workspace_vs/PushExcelDivider/build/mac/PushExcelDivider.app/Contents/Resources/ExcelProcesser.py", line 1, in <module>
import pandas as pd

**Comment by coooldoggy** [comment]
https://github.com/fyears/electron-python-example
https://medium.com/@abulka/electron-python-4e8c807bfa5e

**Comment by coooldoggy** [comment]
https://lahirumadushankablog.wordpress.com/2018/12/17/creating-electron-uis-for-python-projects-and-packaging/

**Comment by coooldoggy** [comment]
https://coding-yoon.tistory.com/30

**Comment by coooldoggy** [comment]
/usr/local/lib/python3.8/site-packages/PyInstaller

**Comment by coooldoggy** [comment]
https://popcorn16.tistory.com/38

**Comment by coooldoggy** [comment]
### VM
https://m.blog.naver.com/alaldi2006/221599593179

**Comment by coooldoggy** [comment]
http://blog.naver.com/PostView.nhn?blogId=ajdkfl6445&logNo=221351895331&categoryNo=0&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView

**Comment by coooldoggy** [comment]
spec file에 추가 후 재빌드 

```
def get_pandas_path():
    import pandas
    pandas_path = pandas.__path__[0]
    return pandas_path

dict_tree = Tree(get_pandas_path(), prefix='pandas', excludes=["*.pyc"])
a.datas += dict_tree
a.binaries = filter(lambda x: 'pandas' not in x[0], a.binaries)
```

`pyinstaller -F xxx.spec`
